name: argoninstaller
description: A beautiful mod installer for minecraft supporting custom repositories and more.
publish_to: 'none'
version: 0.0.10

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  json_annotation: ^4.4.0
  system_theme: ^1.0.1
  flutter_acrylic: ^1.0.0+1
  provider: ^6.0.2
  flutter_native_splash: ^2.0.5
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  window_manager: ^0.2.0
  shared_preferences: ^2.0.8
  flutter_svg: ^1.0.3
  args: ^2.3.0
  flutter_markdown: ^0.6.9
  path_provider: ^2.0.9
  isar: 2.2.1
  isar_flutter_libs: 2.2.1
  file_selector_platform_interface: ^2.0.4
  file_selector_linux:
  file_selector_macos:
  file_selector_windows:
  file_selector: ^0.8.3
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  dependency_validator: ^3.0.0
  isar_generator: 2.2.1
  flutter_lints: ^1.0.0

flutter_native_splash:
  color: '#42a5f5'
  image: assets/argoninstaller.png

flutter:
  assets:
    - assets/Logo.svg
    - assets/argoninstaller.png

  uses-material-design: true

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
